### ISSUE TITLE
Snow not linked to weather

### ISSUE THREAD

**Issue by GlenNicholls** [nhubbard/MagicPlugins#1]
Hey,

So, I´m not sure if this is something that is just turned on during winter. I am testing it out, and it looks like I have to manually enable it to use it. I think something that would be really cool is to make different weather backgrounds based on the weather returned from one of the default weather modules. When it is snowing out according to OpenWeather, you could have something to change the active background of snow when the icons for the default module say that it is snowing. This would also be a really cool addition for rain, sunny, cloudy etc! Might also be cool to add something for weather warnings. Anyways, just a thought.

**Comment by jimga150** [comment]
Maybe you could be the one to make that?

**Comment by nhubbard** [comment]
@GlenNicholls Yeah, I tried that, but it was very confusing. It would involve modifying the weather module to emit sockets  based on the weather, and intercepting those sockets would be tough, since we set origins on the sockets. It also would involve adding grass, sun, rain, et cetera and that would degrade the performance of the mirror heavily. Besides, I just planned on using this module to prevent my display from burning in. It was only an experiment. Thank you for the idea, though!
